# SOPS Configuration for ArgoCD
# This file defines how SOPS encrypts secrets in this repository
#
# Documentation: https://github.com/mozilla/sops
#
# Example usage:
#   Encrypt a file:     sops -e -i secret.yaml
#   Decrypt a file:     sops -d secret.yaml
#   Edit encrypted:     sops secret.yaml
#   Encrypt specific:   sops -e --encrypted-regex '^(data|stringData)$' -i secret.yaml

creation_rules:
  - path_regex: .*\.(yaml|yml|json|env|ini)$
    age: >-
      age13gwk9j9ddstm8ss9n2u8nx6ruh6zgafsapepmjz353tuarwu23hsqffl6t
    encrypted_regex: '^(data|stringData|password|token|key|secret|apiKey|apiToken|credential)$'
