extends: default

ignore:
  - .git/

rules:
  line-length:
    max: 150
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable
  empty-lines:
    max: 2
  new-line-at-end-of-file: enable
  trailing-spaces: enable
