# ArgoCD Application: Nextcloud
# Uses official Nextcloud Helm chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  project: homelab

  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 6.2.4
    helm:
      valuesObject:
        # Nextcloud configuration
        nextcloud:
          host: nextcloud.k8s.home
          username: admin
          password: changeme  # Change this or use existingSecret
          # existingSecret:
          #   enabled: true
          #   secretName: nextcloud-admin
          #   usernameKey: username
          #   passwordKey: password

        # Resource limits for homelab
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        # Persistence
        persistence:
          enabled: true
          storageClass: longhorn
          size: 20Gi

        # Internal PostgreSQL database
        internalDatabase:
          enabled: false

        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: nextcloud
                password: nextcloud-db-pass  # Change this
                database: nextcloud
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 5Gi
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 300m
                memory: 256Mi

        # Redis for caching
        redis:
          enabled: true
          auth:
            enabled: true
            password: redis-pass  # Change this
          master:
            persistence:
              enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
          replica:
            replicaCount: 0

        # Cron job for background tasks
        cronjob:
          enabled: true

        # Ingress - disabled (use Gateway API HTTPRoute separately)
        ingress:
          enabled: false

        # PHP configuration
        phpClientHttpsFix:
          enabled: true
          protocol: https

        # Liveness/Readiness probes
        livenessProbe:
          enabled: true
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          enabled: true
          initialDelaySeconds: 60
          periodSeconds: 30

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
