# SOPS Plugin Configuration for ArgoCD
# This allows ArgoCD to automatically decrypt SOPS-encrypted secrets
---
# ConfigMap with SOPS plugin configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomized-sops
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args:
          - |
            if [ -f kustomization.yaml ] || [ -f kustomization.yml ] || [ -f Kustomization ]; then
              echo "Kustomization file found"
            fi
      generate:
        command: [sh, -c]
        args:
          - |
            if [ -f kustomization.yaml ] || [ -f kustomization.yml ] || [ -f Kustomization ]; then
              kustomize build . | \
              sed 's/kind: Secret/kind: SopsSecret/g' | \
              sops -d --input-type yaml --output-type yaml /dev/stdin
            else
              sops -d .
            fi
      discover:
        find:
          command: [sh, -c, "find . -name '*.enc.yaml' -o -name 'secrets.yaml' -o -name '*secret*.yaml'"]
---
# Get the existing deployment and patch it
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      serviceAccountName: argocd-repo-server
      initContainers:
        - name: install-sops
          image: alpine:3.20
          securityContext:
            allowPrivilegeEscalation: false
          command:
            - sh
            - -c
            - |
              apk add --no-cache curl
              curl -sL https://github.com/getsops/sops/releases/download/v3.11.0/sops-v3.11.0.linux.amd64 -o /custom-tools/sops
              chmod +x /custom-tools/sops
              curl -sL https://github.com/FiloSottile/age/releases/download/v1.2.1/age-v1.2.1-linux-amd64.tar.gz | tar xz -C /tmp
              mv /tmp/age/age /custom-tools/age
              mv /tmp/age/age-keygen /custom-tools/age-keygen
              chmod +x /custom-tools/age /custom-tools/age-keygen
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      containers:
        - name: argocd-repo-server
          image: quay.io/argoproj/argocd:v3.2.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          command:
            - /usr/local/bin/argocd-repo-server
          ports:
            - containerPort: 8081
              name: repo-server
            - containerPort: 8084
              name: metrics
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz?full=true
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /sops-age/keys.txt
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-redis
                  key: auth
                  optional: false
          volumeMounts:
            - mountPath: /usr/local/bin/sops
              name: custom-tools
              subPath: sops
            - mountPath: /usr/local/bin/age
              name: custom-tools
              subPath: age
            - mountPath: /sops-age
              name: sops-age-key
            - mountPath: /app/config/ssh
              name: ssh-known-hosts
            - mountPath: /app/config/tls
              name: tls-certs
            - mountPath: /app/config/gpg/source
              name: gpg-keys
            - mountPath: /app/config/gpg/keys
              name: gpg-keyring
            - mountPath: /tmp
              name: tmp
            - mountPath: /helm-working-dir
              name: helm-working-dir
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /app/config/reposerver/tls
              name: argocd-repo-server-tls
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age-key
          secret:
            secretName: sops-age-key
            optional: false
        - name: ssh-known-hosts
          configMap:
            name: argocd-ssh-known-hosts-cm
            optional: false
        - name: tls-certs
          configMap:
            name: argocd-tls-certs-cm
            optional: false
        - name: gpg-keys
          configMap:
            name: argocd-gpg-keys-cm
            optional: false
        - name: gpg-keyring
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: helm-working-dir
          emptyDir: {}
        - name: argocd-repo-server-tls
          secret:
            secretName: argocd-repo-server-tls
            optional: true
        - name: plugins
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
---
# Service account needs permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-sops-reader
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-sops-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-sops-reader
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd
