# Patch ArgoCD repo-server to support KSOPS (SOPS + Kustomize)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      # Add init container to install KSOPS
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.3.2
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Installing KSOPS..."
              cp /usr/local/bin/ksops /custom-tools/
              cp /usr/local/bin/kustomize /custom-tools/
              echo "KSOPS installation complete"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools

      containers:
        - name: argocd-repo-server
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
          # Mount the AGE key secret
          volumeMounts:
            - mountPath: /sops-age
              name: sops-age-key
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize

          # Set SOPS environment variables
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: SOPS_AGE_KEY_FILE
              value: /sops-age/keys.txt

      # Add volumes
      volumes:
        - name: sops-age-key
          secret:
            secretName: sops-age-key
        - name: custom-tools
          emptyDir: {}
